#cloud-config
users:
  - name: builder
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgLnSoeDQ7s9IldWjk7iOjsY/95c1acvq14QPzVjFJkx/yWl1Om1vbGm3D6hLFZj0BEAaneLm9uLHiJVmio04R5RkcBkP7fVXK5wKChM9f/JxHAaXpDqfLdy7d2Op5XRofrqAl7wYT+4RraunC+sUOssutlxoOHNjJyKDswQvE7jxgOFJdjfzmI0GiN30fX19neyl9NbpelYokb2HIp9QWF4nNuLjZQx1rBDx5Dnpbc52FrUxHHLt7e9JKD7KOKCifTpC8U1KABT5FOpbcOiCk2JSwuv2Fkbhmzsb0j0vT9vxSay9rS4+eBnCWtK8TTagTggCYmQE0D8xriegLfx7L davdunc@406c8f4f8cc8.ant.amazon.com
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDb/OPX08QlSfiL+zsaI15qclH9InemRzGmreTXyfxaXruRznH2somzpdmM254G39ZVZ3cco6Xpgi31PJUlYnvLrEBcuWMX8dtduP/Q+KvV6KWgiagV0o9kfRodZ3CigAJa673ESAPbdzbJGAXxq1YNOTpC9o4w/mqVI5Tw0QU4A4LR5lkhkzOF6uXuvThFDmfPfEpCOv2ITIdVoecnD/h6SU8yY4PI7KFG/kDEXGgHdiYnJ3/fE8L9uupoj1s8SqcE372Ii/Hbq7qbSAHq1xRbDemyPyQWPBlZTxpDJBCyVSEF6CZmnqSvxGDk4bxS+gAp0Iy7mVHYaCJtE6ovqAdH davdunc@u0021cccd85f650db1dcd
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzJRrKkGGzwvPCRhmgToluu+hgjDfQiYFGXKx8FvPDityvFai+g15XTSHf9C8Xi8DIvpmC8jwJx+RA/GsfWOqj/qlP96tcuWtnjlFvFQZi7YYV2BOTKRm9wD6Hcw0byfdjuf52mVCVkAdBMew5ueo4ter1yNP+5ip40kbFXjNuKU50/83alQ4awlI2QXMHhPKHnU9j38Ejmpb+rYmjD67i4Jc+OLOftgPBMyU87AxFMCOOJoDkatlPfIAvJ+3qwhYk8iI9L4QcZ8+is39L7O5W+waFm6scix72R/9EFta9SbUs35kVN6jpHPcvAkz8b3lWkQkLL2fdoI08YmK7ln9hLilYCs5etM13y/+Vnmm2h1/dCWhnwr2PBcQ1edmvIjWvP3O4zHf81rgamDSBLF/3ItUBCAiUpQWkqmlAsvOhP78lCd6oU4HXBlw1oBjFDVGfIj5AktyTqqmVCcsWCsXnE9v2BRBhDfKDEHXey0moJtYoiLJpDBS8c2XdrRrxw8U= kyleknap@a07817a8c9c0.ant.amazon.com
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    gecos: builder account

package_update: true
packages:
  - jq
  - centos-packager
  - fedora-packager
  - fedora-packager-kerberos
  - fedora-packager-yubikey
  - openssl-devel
  - openssl-libs
  - openssl
  - cmake
  - ninja-build
  - fbrnch

runcmd:
  - ['git', 'config', '--global', 'credential.helper', 'store']
  - ['git', 'config', '--global', 'user.name', 'David Duncan']
  - ['git', 'config', '--global', 'user.email', 'davdunc@amazon.com']
  - ['mkdir', '-p', '-m', '0700', '${HOME}/.aws']

write_files:
- encoding: b64
  content: W2RlZmF1bHRdCnJlZ2lvbiA9IHVzLWVhc3QtMQpvdXRwdXQgPSBqc29u
  owner: builder:builder
  path: ${HOME}/.aws/config
  permissions: '0600'
- encoding: b64
  content: ZGF2ZHVuYw==
  owner: builder:builder
  path: ${HOME}/.fedora.upn
  permissions: 760

final_message: Completed configuration for basic userdata file.
