stage: devel
aws:
  instance_role: jenkins-ec2-role
  instance_type: m5d.xlarge
  region: us-east-2
  subnetId: subnet-bb9b99c1
  vpcId: vpc-beb418d5
  boto_profile: image-builder
  ami:
    Name: "CentOS 7.8.*"
    owner_id: "125523088429"
