---
AwsTemplateFormatVersion: 2010-09-09
Description: Adding Support for Storing and Restoring Images
Parameters:
  StoreRestoreS3BucketName:
    Type: String
    Description: The bucket used for storing and restoring AMIs in multiple accounts accross AWS Partitions
    AllowedPattern: >-
      (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
    ConstraintDescription: >-
      See the bucket naming rules at https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html for detailed information on the naming guidelines
Resources:
  StoreRestoreRole:
    Type: AWS::IAM::Role
    Properties: 
      Description: Role for Storing and Restoring AMIs across Regions
      Path: "/"
      RoleName: StoreRestoreRole
      Tags: 
        - Key: centos-2-awsmp
          Value: !Ref "AWS::StackId"
  StoreRestorePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: String
      ManagedPolicyName: String
      Path: "/"
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {  
              "Effect": "Allow",
              "Action": [
                "s3:CompleteMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:InitiateMultipartUpload",
                "s3:ListBucket",
                "s3:ListMultipartUploads",
                "s3:ListParts",
                "s3:PutObject",
                "s3:UploadPart",
                "s3:AbortMultipartUpload",
                "ebs:CompleteSnapshot",
                "ebs:GetSnapshotBlock",
                "ebs:ListChangedBlocks",
                "ebs:ListSnapshotBlocks",
                "ebs:PutSnapshotBlock",
                "ebs:StartSnapshot",
                "ec2:CreateRestoreImageTask",
                "ec2:DescribeStoreImageTasks",
                "ec2:CreateRestoreImageTask",
                "ec2:GetEbsEncryptionByDefault",
                "ec2:DescribeTags"
              ],
              "Resource": "*"
            }
          ]
        }
      Roles: 
        - !Ref StoreRestoreRole
