---
- name: Deploy a builder for awscli
  hosts: localhost
  connection: local

  gather_facts: yes

  vars:
    region: us-east-1
    profile: rpm-builder
    iam_instance_profile: 2P-Lister
    subnet: subnet-0ea8c1b2a8060843b
    ec2_architecture: arm64
    ec2_instance_type:
      x86_64: t3.large
      arm64: t4g.large
    image_id: ami-006073918dcc6f406


  tasks:
    - name: Destroy instances for building images
      amazon.aws.ec2_instance:
        state: terminated
        region: "{{ region }}"
        profile: "{{ profile }}"
        vpc_subnet_id: "{{ subnet }}"
        tags:
          task: rpm-builder

