---
- name: Deploy a builder for CentOS images
  hosts: localhost
  connection: local

  gather_facts: false

  vars:
    fedora_release: 35
    centos_release: 8
    aws_account: 125523088429
    region: us-east-1
    profile: ansible
    aws_instance_role: Tools-Instance
    subnet: subnet-0ea8c1b2a8060843b  # us-east-1 subnet from fedpkg instances
    ec2_architecture: arm64
    ec2_instance_type:
      x86_64: t3.large
      arm64: t4g.large

  tasks:
    - name: Create a proper security group specific to the build images
      debug:
        msg: "TODO"

    - name: Create a security group that matches the requirements
      debug:
        msg: "TODO"

    - name: "Find the CentOS Stream {{ centos_release }} Image in the Fedora account"
      amazon.aws.ec2_ami_info:
        region: "{{ region }}"
        profile: "{{ profile }}"
        owners: "{{ aws_account }}"
        filters:
          architecture: "{{ ec2_architecture }}"
          name: "CentOS Stream 8*"
      register: centos_amis

    - name: "Find the latest Fedora {{ fedora_release }} Image in the Fedora account"
      amazon.aws.ec2_ami_info:
        region: "{{ region }}"
        profile: "{{ profile }}"
        owners: "{{ aws_account }}"
        filters:
          architecture: "{{ ec2_architecture }}"
          name: "Fedora-Cloud-Base-{{ fedora_release }}*"
      register: fedora_amis

    - name: "Get the most recently published CentOS {{ centos_release }} image"
      set_fact:
        centos_ami: "{{ centos_amis.images | sort(attribute='creation_date') | last  }}"

    - name: "Get the most recently published image Fedora {{ fedora_release }} image"
      set_fact:
        fedora_ami: "{{ fedora_amis.images | sort(attribute='creation_date') | last  }}"

    - name: "Deploy {{ centos_ami.name }} instance for building images"
      amazon.aws.ec2_instance:
        name: "package-centos-{{ centos_release }}-{{ ec2_architecture }}"
        region: "{{ region }}"
        profile: "{{ profile }}"
        instance_role: "{{ aws_instance_role }}"
        vpc_subnet_id: "{{ subnet }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        security_group: default
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 20
              delete_on_termination: true
        network:
          assign_public_ip: true
        image_id: "{{ centos_ami.image_id }}"
        user_data: "{{ lookup('file', 'files/builder-instance-userdata.yml') }}"
        tags:
          task: rpm-builder
          maintained_by: davdunc

    - name: "Deploy {{ centos_ami.name }} instance for building images"
      amazon.aws.ec2_instance:
        name: "package-centos-{{ centos_release }}-{{ ec2_architecture }}"
        region: "{{ region }}"
        profile: "{{ profile }}"
        instance_role: "{{ aws_instance_role }}"
        vpc_subnet_id: "{{ subnet }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        security_group: default
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 20
              delete_on_termination: true
        network:
          assign_public_ip: true
        image_id: "{{ centos_ami.image_id }}"
        user_data: "{{ lookup('file', 'files/builder-instance-userdata.yml') }}"
        tags:
          task: rpm-builder
          maintained_by: davdunc

    - name: "Deploy {{ fedora_ami.name }} instance for building images"
      amazon.aws.ec2_instance:
        name: "package-fedora-{{ fedora_release }}-{{ ec2_architecture }}"
        region: "{{ region }}"
        profile: "{{ profile }}"
        instance_role: "{{ aws_instance_role }}"
        vpc_subnet_id: "{{ subnet }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        security_group: default
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 20
              delete_on_termination: true
        network:
          assign_public_ip: true
        image_id: "{{ fedora_ami.image_id }}"
        user_data: "{{ lookup('file', 'files/fedora-instance-userdata.yml') }}"
        tags:
          task: rpm-builder
          maintained_by: davdunc
